"""create_extension_tokens_table

Revision ID: a59cc6ffb28d
Revises: b2c3d4e5f6a8
Create Date: 2026-09-26 12:20:37.998158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59cc6ffb28d'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ext_token_user_active', 'extension_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_extension_tokens_id'), 'extension_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_extension_tokens_revoked_at'), 'extension_tokens', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_extension_tokens_token_hash'), 'extension_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_extension_tokens_user_id'), 'extension_tokens', ['user_id'], unique=False)
    # Ensure idx_kchunk_hnsw_cosine is preserved on pgvector
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("CREATE INDEX IF NOT EXISTS idx_kchunk_hnsw_cosine ON knowledge_chunks USING hnsw (embedding vector_cosine_ops);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_subscriptions_endpoint'), table_name='push_subscriptions')
    op.create_unique_constraint(op.f('uq_push_subscriptions_endpoint'), 'push_subscriptions', ['endpoint'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_notif_user_status', table_name='notifications')
    op.create_index(op.f('idx_kchunk_hnsw_cosine'), 'knowledge_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_extension_tokens_user_id'), table_name='extension_tokens')
    op.drop_index(op.f('ix_extension_tokens_token_hash'), table_name='extension_tokens')
    op.drop_index(op.f('ix_extension_tokens_revoked_at'), table_name='extension_tokens')
    op.drop_index(op.f('ix_extension_tokens_id'), table_name='extension_tokens')
    op.drop_index('idx_ext_token_user_active', table_name='extension_tokens')
    op.drop_table('extension_tokens')
    # ### end Alembic commands ###
