"""
Pydantic schemas for Gmail API responses.
Provides safe, normalized representations of Gmail profiles, messages, and attachments.
CRITICAL SECURITY: Never exposes access tokens, refresh tokens, or client credentials.
"""
from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field


class GmailProfileResponse(BaseModel):
    """Normalized profile information from Gmail."""
    email: str = Field(..., description="Email address associated with the Gmail account")
    messages_total: int = Field(0, description="Total number of messages in the mailbox")
    threads_total: int = Field(0, description="Total number of threads in the mailbox")
    history_id: Optional[str] = Field(None, description="Current history ID of the mailbox")

    model_config = ConfigDict(from_attributes=True)


class GmailAttachmentMetadata(BaseModel):
    """Metadata for an email attachment without downloading payload bytes."""
    attachment_id: Optional[str] = Field(None, description="Gmail attachment ID for future on-demand retrieval")
    filename: str = Field(..., description="Original filename of the attachment")
    mime_type: str = Field(..., description="MIME type of the attachment")
    size: int = Field(0, description="File size in bytes")

    model_config = ConfigDict(from_attributes=True)


class GmailMessageSummary(BaseModel):
    """Summary item for email message lists."""
    id: str = Field(..., description="Gmail message ID")
    thread_id: str = Field(..., description="Gmail thread ID")
    subject: str = Field(..., description="Decoded email subject")
    sender: str = Field(..., description="Decoded sender (From: header)")
    recipients: List[str] = Field(default_factory=list, description="List of recipient email addresses")
    timestamp: Optional[str] = Field(None, description="ISO-8601 UTC timestamp of message")
    snippet: str = Field("", description="Short summary snippet generated by Gmail")
    labels: List[str] = Field(default_factory=list, description="Gmail label IDs applied to this message")
    is_unread: bool = Field(False, description="True if UNREAD label is present")
    has_attachments: bool = Field(False, description="True if message contains attachments")

    model_config = ConfigDict(from_attributes=True)


class GmailMessageDetail(BaseModel):
    """Full message details including normalized safe body text and attachment metadata."""
    id: str = Field(..., description="Gmail message ID")
    thread_id: str = Field(..., description="Gmail thread ID")
    subject: str = Field(..., description="Decoded email subject")
    sender: str = Field(..., description="Decoded sender (From: header)")
    recipients: List[str] = Field(default_factory=list, description="List of recipient email addresses")
    cc: List[str] = Field(default_factory=list, description="List of CC email addresses")
    bcc: List[str] = Field(default_factory=list, description="List of BCC email addresses")
    timestamp: Optional[str] = Field(None, description="ISO-8601 UTC timestamp of message")
    snippet: str = Field("", description="Short summary snippet")
    body_plain: Optional[str] = Field(None, description="Plain text body of the email")
    body_html_text: Optional[str] = Field(
        None,
        description="Sanitized plain text extracted from HTML part, with scripts/styles/tags safely stripped"
    )
    labels: List[str] = Field(default_factory=list, description="Gmail label IDs")
    is_unread: bool = Field(False, description="True if UNREAD label is present")
    attachments: List[GmailAttachmentMetadata] = Field(
        default_factory=list,
        description="List of attachment metadata records (no contents downloaded)"
    )

    model_config = ConfigDict(from_attributes=True)


class GmailMessageListResponse(BaseModel):
    """Paginated list of Gmail message summaries."""
    messages: List[GmailMessageSummary] = Field(default_factory=list, description="List of message summaries")
    next_page_token: Optional[str] = Field(None, description="Token for retrieving subsequent page")
    result_size_estimate: int = Field(0, description="Estimated total matching messages")

    model_config = ConfigDict(from_attributes=True)
