"""
Pydantic schemas for Gmail API responses.
Provides safe, normalized representations of Gmail profiles, messages, and attachments.
CRITICAL SECURITY: Never exposes access tokens, refresh tokens, or client credentials.
"""
from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field


class GmailProfileResponse(BaseModel):
    """Normalized profile information from Gmail."""
    email: str = Field(..., description="Email address associated with the Gmail account")
    messages_total: int = Field(0, description="Total number of messages in the mailbox")
    threads_total: int = Field(0, description="Total number of threads in the mailbox")
    history_id: Optional[str] = Field(None, description="Current history ID of the mailbox")

    model_config = ConfigDict(from_attributes=True)


class GmailAttachmentMetadata(BaseModel):
    """Metadata for an email attachment without downloading payload bytes."""
    attachment_id: Optional[str] = Field(None, description="Gmail attachment ID for future on-demand retrieval")
    filename: str = Field(..., description="Original filename of the attachment")
    mime_type: str = Field(..., description="MIME type of the attachment")
    size: int = Field(0, description="File size in bytes")

    model_config = ConfigDict(from_attributes=True)


class GmailMessageSummary(BaseModel):
    """Summary item for email message lists."""
    id: str = Field(..., description="Gmail message ID")
    thread_id: str = Field(..., description="Gmail thread ID")
    subject: str = Field(..., description="Decoded email subject")
    sender: str = Field(..., description="Decoded sender (From: header)")
    recipients: List[str] = Field(default_factory=list, description="List of recipient email addresses")
    timestamp: Optional[str] = Field(None, description="ISO-8601 UTC timestamp of message")
    snippet: str = Field("", description="Short summary snippet generated by Gmail")
    labels: List[str] = Field(default_factory=list, description="Gmail label IDs applied to this message")
    is_unread: bool = Field(False, description="True if UNREAD label is present")
    has_attachments: bool = Field(False, description="True if message contains attachments")

    model_config = ConfigDict(from_attributes=True)


class GmailMessageDetail(BaseModel):
    """Full message details including normalized safe body text and attachment metadata."""
    id: str = Field(..., description="Gmail message ID")
    thread_id: str = Field(..., description="Gmail thread ID")
    subject: str = Field(..., description="Decoded email subject")
    sender: str = Field(..., description="Decoded sender (From: header)")
    recipients: List[str] = Field(default_factory=list, description="List of recipient email addresses")
    cc: List[str] = Field(default_factory=list, description="List of CC email addresses")
    bcc: List[str] = Field(default_factory=list, description="List of BCC email addresses")
    timestamp: Optional[str] = Field(None, description="ISO-8601 UTC timestamp of message")
    snippet: str = Field("", description="Short summary snippet")
    body_plain: Optional[str] = Field(None, description="Plain text body of the email")
    body_html_text: Optional[str] = Field(
        None,
        description="Sanitized plain text extracted from HTML part, with scripts/styles/tags safely stripped"
    )
    labels: List[str] = Field(default_factory=list, description="Gmail label IDs")
    is_unread: bool = Field(False, description="True if UNREAD label is present")
    attachments: List[GmailAttachmentMetadata] = Field(
        default_factory=list,
        description="List of attachment metadata records (no contents downloaded)"
    )

    model_config = ConfigDict(from_attributes=True)


class GmailMessageListResponse(BaseModel):
    """Paginated list of Gmail message summaries."""
    messages: List[GmailMessageSummary] = Field(default_factory=list, description="List of message summaries")
    next_page_token: Optional[str] = Field(None, description="Token for retrieving subsequent page")
    result_size_estimate: int = Field(0, description="Estimated total matching messages")

    model_config = ConfigDict(from_attributes=True)


class GmailReplyDraftRequest(BaseModel):
    """Request payload for on-demand smart reply drafting."""
    tone: Optional[str] = Field(
        default="professional",
        description="Desired tone for the reply (e.g., 'professional', 'friendly', 'concise', 'formal', 'direct')",
    )
    custom_instructions: Optional[str] = Field(
        default=None,
        max_length=1000,
        description="Optional custom user guidelines or specific facts to incorporate into the reply",
    )
    include_thread_context: bool = Field(
        default=True,
        description="Whether to retrieve and analyze prior thread messages if available",
    )

    model_config = ConfigDict(from_attributes=True)


class GmailReplyDraftSaveRequest(BaseModel):
    """Request payload for saving or autosaving a Smart Reply draft."""
    reply_body: str = Field(..., description="Draft reply body text to persist")
    tone: Optional[str] = Field(default="professional", description="Tone of the reply")
    custom_instructions: Optional[str] = Field(
        default=None,
        max_length=1000,
        description="Optional custom user notes or guidelines",
    )
    placeholders_detected: List[str] = Field(
        default_factory=list,
        description="List of detected placeholder tags (e.g. '[Your Name]') requiring review",
    )
    thread_id: Optional[str] = Field(None, description="Optional Gmail thread ID")
    subject: Optional[str] = Field(None, description="Optional reply subject")
    recipient: Optional[str] = Field(None, description="Optional recipient email/name")
    gmail_draft_id: Optional[str] = Field(None, description="Associated Gmail API draft ID if saved to mailbox")

    model_config = ConfigDict(from_attributes=True)


class GmailReplyDraftResponse(BaseModel):
    """Generated or persisted smart reply draft response."""
    id: Optional[str] = Field(None, description="Database record ID if persisted")
    message_id: str = Field(..., description="ID of the email message being replied to")
    thread_id: Optional[str] = Field(None, description="Gmail thread ID")
    gmail_draft_id: Optional[str] = Field(None, description="Associated Gmail API draft ID if saved to mailbox")
    gmail_web_url: Optional[str] = Field(None, description="Direct URL to view/edit draft in Gmail")
    subject: str = Field(..., description="Suggested reply subject")
    recipient: str = Field(..., description="Sender of the original email to reply to")
    reply_body: str = Field(..., description="Generated/saved reply email body text")
    tone_used: str = Field(..., description="Tone applied in generation or save")
    custom_instructions: Optional[str] = Field(None, description="Custom instructions used")
    placeholders_detected: List[str] = Field(
        default_factory=list,
        description="List of detected placeholder tags requiring user review",
    )
    created_at: Optional[str] = Field(None, description="ISO timestamp of draft creation")
    updated_at: Optional[str] = Field(None, description="ISO timestamp of last update")

    model_config = ConfigDict(from_attributes=True)

